config/routes.rb
StoreManager::Application.routes.draw do
  get "unauthorized/index"
  get "unauthorized/profile"
  get "unauthorized/access_denied"
  match 'about' => 'unauthorized#about'
  devise_for :users do
    get '/'=> 'devise/sessions#new'
  end

  get 'users/edit'
  match 'users/profile' => 'user#profile'
  match 'users/edit_profile' => 'user#edit_profile'
  match 'users/update_profile' => 'user#update_profile'
  match 'unauthorized/index' => 'unauthorized#index'
  match 'users/current_request' => 'user#current_request'
  match 'users/user_cart_detail' => 'user#user_cart_detail'
  match 'users/user_cart_delete' => 'user#user_cart_delete'
  match 'users/report_list' => 'user#report_list'
  match 'users/notification' => 'user#notification'
  match 'users/notification_all' => 'user#notification_all'
  match 'users/reply_notification' => 'user#reply_notification'
  match 'users/create_reply_notification' => 'user#create_reply_notification'
  match 'users/delete_notification' => 'user#delete_notification'
  match 'users/edit_request' => 'user#edit_request'
  match 'users/update' => 'user#update'
  match 'users/destroy' => 'user#destroy'
  match 'users/compose_notification'=>'user#compose_notification'
  match 'users/create_compose_notification' => 'user#create_compose_notification'
  match 'users/change_password' => 'user#change_password'
  match 'users/update_password' => 'user#update_password'
  match 'users/send_notification_list' => 'user#send_notification_list'
  match 'users/read_notification' => 'user#read_notification'
  match 'users/notification_detail' => 'user#notification_detail'
  match 'users/move_to_trash' => 'user#move_to_trash'
  match 'users/trash_list' => 'user#trash_list'
  resources :location

  resources :category

  match 'admin/users_list' => 'admin#users_list'
  match 'admin/edit_user' => 'admin#edit_user'
  match 'admin/update_user' => 'admin#update_user'
  match 'admin/block_user' => 'admin#block_user'
  match 'admin/show_user' => 'admin#show_user'
  match 'admin/damage_list'=> 'admin#damage_list'
  match 'admin/restore_damage'=> 'admin#restore_damage'
  match 'admin/update_product' => 'admin#update_product'

  resources :product do
    collection do
      get 'move_to_damage_list'
      post 'move_to_damage'
    end
  end
  match 'product/search_result' => 'product#search_result'
  resources :cart, :except=> [:show]
  match 'cart/product_detail' => 'cart#product_detail'
  match 'cart/select_quantity' => 'cart#select_quantity'
  match 'cart/cart_detail' => 'cart#cart_detail'
  match 'cart/edit_item' => 'cart#edit_item'
  match 'cart/item_destroy' => 'cart#item_destroy'
  match 'cart/update_item' => 'cart#update_item'
  match 'cart/cart_destroy' => 'cart#cart_destroy'
  match 'cart/create_cart' => 'cart#create_cart'
  match 'cart/submit_cart' => 'cart#submit_cart'
  match 'cart/delete' => 'cart#delete'

  resources :item
  match 'item/item_detail/:id' => 'item#item_detail'
  match 'item/select_item/:id' => 'item#select_item'
  match 'item/create_item' => 'item#create_item'
  post 'item/new'
  match 'item/item_status' => 'item#item_status'

  match 'request/index' => 'request#index'
  match 'request/cart_detail' => 'request#cart_detail'
  match 'request/approve_cart' => 'request#approve_cart'
  match 'request/approve_item' => 'request#approve_item'
  match 'request/cart_delete' => 'request#cart_delete'
  match 'request/item_delete' => 'request#item_delete'
  match 'request/edit_item' => 'request#edit_item'
  match 'request/move_to_que' => 'request#move_to_que'
  match 'request/que_list' => 'request#que_list'
  match 'request/record_list' => 'request#record_list'
  match 'request/recieve_item_list' => 'request#recieve_item_list'
  match 'request/send_notification' => 'request#send_notification'
  match 'request/recieve_item' => 'request#recieve_item'
  match 'request/create_notification' => 'request#create_notification'
  match 'request/move_to_damage_list' => 'request#move_to_damage_list'
  match 'request/move_to_damage' => 'request#move_to_damage'
  post 'request/search'
  put 'request/update'

  root :to => 'devise/sessions#new'

end

app/models/item.rb
class Item < ActiveRecord::Base
  attr_accessible :cart_id, :product_id, :quantity, :total, :user_id, :status,
  								:return_date, :purchasing_date
  scope :of_current_cart, lambda { |cart| where(:cart_id=> cart) }
  belongs_to :cart
  belongs_to :product
  belongs_to :user
  validates_presence_of :return_date, :purchasing_date
  validates_format_of :return_date, with:/\A\d{4}\-\d{2}\-\d{2}\z/
	validate :past_dates
	validate :past_purchasing_date

	delegate :name, :price, :quantity, :to => :product, :prefix => true

  def past_dates
	 if self.return_date && self.return_date.to_date < self.purchasing_date.to_date
	 		self.errors[:base] << "Date is Invalid"
	 	end
	end

	def past_purchasing_date
		if self.purchasing_date && self.purchasing_date.to_date < Date.today.to_date
	 		self.errors[:base] << "Date is Invalid"
	 	end
	end

	def approve_link
		if self.purchasing_date == Date.today.to_date
			return true
		else
			return false
		end
	end

	def date_status
		(self.return_date.to_date - self.purchasing_date.to_date).to_i
	end

	def item_status(product_id)
  	cart = Cart.where(:status =>true)
  	items = []
  	total_quantity_requested = []
  	cart.map{|c| items += c.items.where(:product_id=>product_id)}
    items.map{|qty| total_quantity_requested << qty.quantity}
    return total_quantity_requested.sum
	end

	def item_available(total_quantity, product_quantity)
		quantity = total_quantity - product_quantity
		if quantity > 0
			return "#{quantity} available out of #{total_quantity}"
		else
			return "Item is on Demand"
		end
	end
end

app/controllers/item_controller.rb
class ItemController < ApplicationController
	before_filter :authenticate_user!
	before_filter :is_active_user

	def index
		if session[:cart_id]
			session[:cart_id] = nil
		end
			@cart = Cart.find(params[:id])
			session[:cart_id] = @cart.id
    @items = Item.of_current_cart(session[:cart_id])
  end

  def item_status
  	@product = Product.find(params[:id])
  	cart = Cart.where(:status =>true)
  	items = []
  	cart.map{|c| items += c.items.where(:product_id=>@product.id)}
  	@items = items
  end

  def new
  	@category = Category.all
  	@location = Location.all
  	if params[:post].blank? && params[:loc].blank?
  		@products = Product.all
	  elsif params[:post] || params[:loc]
  		conditions ={}
  		category_id = params[:post][:category]unless params[:post][:category].blank?
  		location_id = params[:loc][:location]unless params[:loc][:location].blank?
  		if category_id && location_id
  			conditions[:category_id] = params[:post][:category]
  			conditions[:location_id] = params[:loc][:location]
  		elsif category_id
  			conditions[:category_id] = params[:post][:category]
  		elsif location_id
  			conditions[:location_id] = params[:loc][:location]
  		end
  		@products = Product.find(:all, :conditions=> conditions)
 	  end
  end

  def create
  	@item = Item.new(params[:item])
		if @item.save
			flash[:notice] = "Successfully created..."
			redirect_to item_index_path
		else
			flash[:error] = @item.errors.full_messages.to_sentence
			render 'new'
  	end
  end

  def edit
    @item = Item.find(params[:id])
  end

	def update
		@item = Item.find(params[:item][:id])
		if @item.update_attributes(params[:item])
			price = @item.product.price
			quantity = @item.quantity
			item_price = quantity * price
			@item.update_attributes!(:total=>item_price)
			flash[:notice] = "Successfully Updated..."
			@items = Item.of_current_cart(session[:cart_id])
			render 'index'
		else
			flash[:error] = @item.errors.full_messages.to_sentence
			render 'edit'
		end
	end

  def destroy
    @item = Item.find(params[:id])
    if @item.destroy
    	flash[:notice] = "Successfully Deleted..."
    else
    	flash[:error] = @item.errors.full_messages.to_sentence
    end
    @items = Item.of_current_cart(session[:cart_id])
    render 'index'
  end

	def select_item
		@product = Product.find(params[:id])
	end

	def item_detail
		@product = Product.find(params[:id])
	end

	def create_item
		@cart = Cart.find(session[:cart_id])
	 	if @cart
			@product = Product.find(params[:product][:id])
			quantity_value = params[:product][:quantity]
			@item = @cart.add_product_to_item(@product.id)
			@item.purchasing_date = params[:product][:purchasing_date]
	 		@item.quantity = quantity_value
	 		@item.return_date = params[:return_date_of_item]
	 		@item.total = @item.product.price * quantity_value.to_f
	  	if @item.save
	  		@items = Item.of_current_cart(session[:cart_id])
	 			flash[:notice] = "Added Successfully"
	 			render 'index'
			else
				flash[:error] = @item.errors.full_messages.to_sentence
				render 'select_item'
			end
		end
	end
end

app/helpers/item_helper.rb
module ItemHelper
	def item_link(item)
		links = ""
		links += link_to 'Edit', action:'edit', id:item.id 
		links += " | "
		links += link_to 'Delete', item_path(item), method:'delete'
		return links
	end

	def add_item_link(product)
		links = ""
		links += link_to 'View', action:'item_detail', id:product.id 
		links += " | "
		links += link_to 'Add', action:'select_item', id:product.id
		return links
	end

end

app/views/item/_search_product.html.erb
<%= form_tag :controller => 'item', :action => 'new', :method => 'post' do %>
  <%= label_tag :category, "Category" %>
  <%= collection_select :post, :category, @category, :id, :name , prompt:"All" %>
  <%= label_tag :location, "Location" %>
  <%= collection_select :loc, :location, @location, :id, :location_name, prompt:"All"%>
  <%= submit_tag "Search" %>   
<% end %>

app/views/item/edit.html.erb
<div class="span8 well">
	<div style="margin-left:10%;" class="row">
		<%= form_for @item, url:{:action=>'update'}, method:'put' do |f| -%>
			<%= f.hidden_field :id %>
			<%= f.label :name, "Name" %>
			<%= @item.product_name %><br>
		  <%= f.label :quantity, "Quantity" %>
		 	<%= f.select :quantity,(1..((@item.product_quantity).to_i)).to_a ,{}, :class => "span2" %>
		 	<%= f.label :purchasing_date, "Purchasing Date" %>
		 	<%= f.text_field :purchasing_date, id:'datepicker1' %>
		 	<%= f.label :return_date, "Return Date" %>
		 	<%= f.text_field :return_date, id:'datepicker' %>
		 	<%= f.submit "update", :disable_with => 'updating...', class:'btn btn-primary' %>
		<% end %>
	</div>
</div>

app/views/item/index.html.erb
<table cellpadding="0" cellspacing="0" border="0" class="table table-striped table-bordered" id="data_tables">
	<thead>
		<tr>
			<th> Product Name</th>
			<th> Quantity Requested</th>
			<th> Price/unit</th>
			<th> Total</th>
			<th> Purchasing Date</th>
			<th> Return Date</th>
			<th> Item Availability </th>
			<th> Actions</th>
		</tr>
	</thead>

	<tbody>
		<% @items.each do |item| %>
		<tr>
			<td><%= link_to item.product_name, item_item_status_path(id:item.product_id),
			method:'post'
			 %> </td>

			<td> <%= item.quantity %> </td>
			<td> <%= item.product_price %> </td>
			<td> <%= item.total%></td>
			<td> <%= item.purchasing_date %></td>
			<td> <%= item.return_date %></td>
			<td> <%=item.item_available(item.product.quantity,
										 item.item_status(item.product_id))%></td>
			<td><%= item_link(item).html_safe%> </td>
		</tr>
		<% end %>
	</tbody>
</table>
<%= link_to 'Add Items', new_item_path, class:'btn btn-primary' %><br>
<br>
<%= link_to 'Back to Cart', cart_index_path, class:'btn btn-primary' %>

app/views/item/item_detail.html.erb
<div class="span12 well">
	<div style="width:30%;float:left;" class="image_div">
			<%=image_tag(@product.image, size:'200x200') %>
		</div>
	<div style="width:70%;float:right;" class ="table_div">
		<table cellpadding="0" cellspacing="0" border="0" class="table table-striped table-bordered">
			<thead>
				<tr>
					<th> Field </th>
					<th> Value </th>
				</tr>
			</thead>
			<tbody>
				<tr>
					<td> Name </td>
					<td> <%= @product.name %></td>
				</tr>
				<tr>
					<td> Quantity </td>
					<td> <%= @product.quantity %></td>
				</tr>
				<tr>
					<td> Price </td>
					<td> <%= @product.price %></td>
				</tr>
				<tr>
					<td> Purchase Date </td>
					<td> <%= @product.purchase_date %></td>
				</tr>
				<tr>
					<td> Location </td>
					<td> <%= @product.location_location_name %></td>
				</tr>
				<tr>
					<td> Category </td>
					<td> <%= @product.category_name %></td>
				</tr>
			</tbody>
		</table>
	</div>
</div>
<div style="float:left;margin-right:5%;">
	<%= button_to "back", new_item_path, method:'get', class:"btn btn-primary" %>
</div>

app/views/item/item_status.html.erb
<div class ="span8 well">

	<table cellpadding="0" cellspacing="0" border="0" class="table table-striped table-bordered">
		<thead>
			<th> User</th>
			<th> Product Name</th>
			<th> Quantity requested</th>
			<th> return Date</th>
			<th> Return Time </th>
		</thead>

		<% total_quantity = [] %>
		<tbody>
			<% @items.each do |item| %>
			<tr>
				<td><%= item.user.user_detail.full_name%></td>
				<td><%= item.product.name%></td>
				<% total_quantity << item.quantity %>
				<td><%= item.quantity%> </td>
				<td><%= item.return_date%> </td>
				<td> <%= item.date_status%></td>
			</tr>
			<% end %>
		</tbody>
	</table>
	Total Quantity Requested :<%= total_quantity.sum %><br>
	Quantity Available :<%= @product.quantity %><br><br>
<strong>Item Available :<%= @product.quantity - total_quantity.sum %></strong>
</div>

app/views/item/new.html.erb
<table cellpadding="0" cellspacing="0" border="0" class="table table-striped table-bordered" id="data_tables">
	<thead>
		<tr>
			<th> Name </th>
			<th> Category</th>
			<th> Location</th>
			<th> Quantity</th>
			<th> Price</th>
			<th> Actions</th>
		</tr>
	</thead>

	<tbody>
		<%= render 'search_product' %>
		<% @products.each do |product| %>
		<tr>
			<td><%= product.name %> </td>
			<td><%= product.category_name %> </td>
			<td><%= product.location_location_name %> </td>
			<td><%= product.quantity%> </td>
			<td><%= product.price%></td>
			<td><%= add_item_link(product).html_safe %> </td>
		</tr>
		<% end %>
	</tbody>
</table>
<%= link_to "Back", item_index_path(:id=>session[:cart_id]), class:'btn btn-primary' %>

app/views/item/select_item.html.erb
<div class = "span6 well">
	<%= form_for @product, url:{action:'create_item'}, method:'post' do |f| -%>
		<%= f.hidden_field :id %><br>
		<i>Product Name :</i> <%= @product.name%><br>
		<%= image_tag(@product.image, size:'100x100')%><br>
		<i><%= f.label :quantity, "Enter Quantity :" %></i>
		<%= f.select :quantity,(1..((@product.quantity).to_i)).to_a ,{},
													 :class => "span2" %>
		<br>
		<%= f.label :purchasing_date, "Purchasing Date" %>
		<%= f.text_field :purchasing_date, value:Date.today, :id=>'datepicker1' %>
		<%= f.label :return_date_of_item, "Returning date of item" %>
		<%= text_field_tag :return_date_of_item, params[:return_date_of_item], :id=>'datepicker'%><br>
		<%= f.submit "Submit", :disable_with => 'Submiting...', class:'btn btn-primary' %>
	<% end %>
	<%= link_to "Cancel", item_new_path, class:'btn btn-primary' %>
</div>