config/routes.rb
StoreManager::Application.routes.draw do
  get "unauthorized/index"
  get "unauthorized/profile"
  get "unauthorized/access_denied"
  match 'about' => 'unauthorized#about'
  devise_for :users do
    get '/'=> 'devise/sessions#new'
  end

  get 'users/edit'
  match 'users/profile' => 'user#profile'
  match 'users/edit_profile' => 'user#edit_profile'
  match 'users/update_profile' => 'user#update_profile'
  match 'unauthorized/index' => 'unauthorized#index'
  match 'users/current_request' => 'user#current_request'
  match 'users/user_cart_detail' => 'user#user_cart_detail'
  match 'users/user_cart_delete' => 'user#user_cart_delete'
  match 'users/report_list' => 'user#report_list'
  match 'users/notification' => 'user#notification'
  match 'users/notification_all' => 'user#notification_all'
  match 'users/reply_notification' => 'user#reply_notification'
  match 'users/create_reply_notification' => 'user#create_reply_notification'
  match 'users/delete_notification' => 'user#delete_notification'
  match 'users/edit_request' => 'user#edit_request'
  match 'users/update' => 'user#update'
  match 'users/destroy' => 'user#destroy'
  match 'users/compose_notification'=>'user#compose_notification'
  match 'users/create_compose_notification' => 'user#create_compose_notification'
  match 'users/change_password' => 'user#change_password'
  match 'users/update_password' => 'user#update_password'
  match 'users/send_notification_list' => 'user#send_notification_list'
  match 'users/read_notification' => 'user#read_notification'
  match 'users/notification_detail' => 'user#notification_detail'
  match 'users/move_to_trash' => 'user#move_to_trash'
  match 'users/trash_list' => 'user#trash_list'
  resources :location

  resources :category

  match 'admin/users_list' => 'admin#users_list'
  match 'admin/edit_user' => 'admin#edit_user'
  match 'admin/update_user' => 'admin#update_user'
  match 'admin/block_user' => 'admin#block_user'
  match 'admin/show_user' => 'admin#show_user'
  match 'admin/damage_list'=> 'admin#damage_list'
  match 'admin/restore_damage'=> 'admin#restore_damage'
  match 'admin/update_product' => 'admin#update_product'

  resources :product do
    collection do
      get 'move_to_damage_list'
      post 'move_to_damage'
    end
  end
  match 'product/search_result' => 'product#search_result'
  resources :cart, :except=> [:show]
  match 'cart/product_detail' => 'cart#product_detail'
  match 'cart/select_quantity' => 'cart#select_quantity'
  match 'cart/cart_detail' => 'cart#cart_detail'
  match 'cart/edit_item' => 'cart#edit_item'
  match 'cart/item_destroy' => 'cart#item_destroy'
  match 'cart/update_item' => 'cart#update_item'
  match 'cart/cart_destroy' => 'cart#cart_destroy'
  match 'cart/create_cart' => 'cart#create_cart'
  match 'cart/submit_cart' => 'cart#submit_cart'
  match 'cart/delete' => 'cart#delete'

  resources :item
  match 'item/item_detail/:id' => 'item#item_detail'
  match 'item/select_item/:id' => 'item#select_item'
  match 'item/create_item' => 'item#create_item'
  post 'item/new'
  match 'item/item_status' => 'item#item_status'

  match 'request/index' => 'request#index'
  match 'request/cart_detail' => 'request#cart_detail'
  match 'request/approve_cart' => 'request#approve_cart'
  match 'request/approve_item' => 'request#approve_item'
  match 'request/cart_delete' => 'request#cart_delete'
  match 'request/item_delete' => 'request#item_delete'
  match 'request/edit_item' => 'request#edit_item'
  match 'request/move_to_que' => 'request#move_to_que'
  match 'request/que_list' => 'request#que_list'
  match 'request/record_list' => 'request#record_list'
  match 'request/recieve_item_list' => 'request#recieve_item_list'
  match 'request/send_notification' => 'request#send_notification'
  match 'request/recieve_item' => 'request#recieve_item'
  match 'request/create_notification' => 'request#create_notification'
  match 'request/move_to_damage_list' => 'request#move_to_damage_list'
  match 'request/move_to_damage' => 'request#move_to_damage'
  post 'request/search'
  put 'request/update'

  root :to => 'devise/sessions#new'

end

app/models/cart.rb
class Cart < ActiveRecord::Base
  attr_accessible :total_price, :user_id, :status, :move_to_que
  validates :user_id, :presence=>true
  scope :of_current_user, lambda { |user| where(:user_id=> user.id,
                                    :status=>false) }
  has_many :items, :dependent=>:destroy
  belongs_to :user

  def add_product_to_item(product_id)
    current_item = items.find_by_product_id(product_id)
		if current_item
			current_item.quantity += 1
		else
			current_item = items.build(:product_id => product_id,
                                  :user_id=>self.user_id)
		end
			current_item
  end

  def whole_price
		items.to_a.sum {|item| item.total}
	end
end

app/controllers/cart_controller.rb
class CartController < ApplicationController
	before_filter :authenticate_user!
	before_filter :is_active_user

	def index
		@carts = Cart.of_current_user(current_user)
	end

	def new
		@cart = Cart.new
		@products = Product.all
	end

	def create_cart
		carts = Cart.of_current_user(current_user)
		if carts.count<1
			cart = Cart.new(:user_id => current_user.id)
			if cart.save
				flash[:notice] = "Cart created Succesflly"
			else
				flash[:error] = cart.errors.full_messages.to_sentence
			end
		else
			flash[:error] = "please submit the existing cart"
		end
		redirect_to cart_index_path
	end

	def submit_cart
		cart = Cart.find(params[:id])
		if cart.update_attributes(:status =>true, :total_price=> cart.whole_price)
			flash[:notice] = "Cart Submitted Succesflly"
		else
			flash[:error] = cart.errors.full_messages.to_sentence
		end
		redirect_to cart_index_path
	end

	def select_quantity
		@product = Product.find(params[:id])
	end

	def product_detail
		@product = Product.find(params[:id])
	end

	def cart_detail
		cart = Cart.find(params[:id])
		@items = cart.items
	end

	def edit_item
		@item = Item.find(params[:id])
	end

	def update_item
		@item = Item.find(params[:item][:id])
		cart_total_price = @item.quantity * @item.product.price
		if @item.update_attributes(params[:item])
			@item.cart.update_attributes!(:total=>cart.total_price)
			flash[:notice] = "Succesfully Updated"
			redirect_to cart_index_path
		else
			flash[:error] = @item.errors.full_messages.to_sentence
			render 'edit_item'
		end
	end

	def delete
		@cart = Cart.find(params[:id])
		if @cart.destroy
			flash[:notice] = "Deleted Succesfully"
		else
			flash[:error] = @cart.errors.full_messages.to_sentence
		end
		redirect_to cart_index_path
	end
end

app/helpers/cart_helper.rb
module CartHelper
	def cart_link(product)
		links = ""
		links += link_to 'view', action:'product_detail', id:product.id 
		links += " | "
		links += link_to 'request', action:'select_quantity', id:product.id, method:'post'
		return links
	end

	def item_link(cart)
		links = ""
		links += link_to 'details', action:'cart_detail', id:cart.id 
		links += " | "
		links += link_to 'Delete', action:'cart_destroy', id:cart.id, method:'post'
		return links
	end

	def item_action(item)
		links = ""
		links += link_to 'edit', action:'edit_item', id:item.id 
		links += " | "
		links += link_to 'Delete', action:'item_destroy', method:'delete'
		return links
	end
end

app/views/cart/cart_detail.html.erb
<table cellpadding="0" cellspacing="0" border="0" class="table table-striped table-bordered" id="data_tables">
	<thead>
		<tr>
			<th> Product </th>
			<th> Quantity</th>
			<th> Total </th>
			<th> Action</th>
		</tr>
	</thead>

	<tbody>
		<% @items.each do |item| %>
		<tr>
			<td><%= item.product_name %> </td>
			<td> <%= item.quantity %></td>
			<td> <%= item.total %></td>
			<td> <%= item_action(item).html_safe %></td>
		</tr>
		<% end %>
	</tbody>
</table>

app/views/cart/edit_item.html.erb
<div class="span8 well">
	<div style="margin-left:10%;" class="row">
		<%= form_for @item, url:{:action=>'update_item'}, method:'post' do |f| -%>
			<%= f.hidden_field :id %>
			<%= f.label :name, "Name" %>
			<%= @item.product_name %><br>
		  <%= f.label :quantity, "Quantity" %>
		 	<%= f.text_field :quantity %>
		 	<%= f.submit "update", :disable_with => 'updating...', class:'btn btn-primary' %>
		<% end %>
	</div>
</div>

app/views/cart/index.html.erb
<table cellpadding="0" cellspacing="0" border="0" class="table table-striped table-bordered" id="data_tables">
	<thead>
		<tr>
			<th> Sl.No</th>
			<th> Total Price </th>
			<th> Status</th>
			<th> Action</th>
		</tr>
	</thead>

	<tbody>
		<% @carts.each_with_index do |cart, index| %>
		<% cart.total_price = cart.whole_price%>
		<tr>
			<td> <%= index+1 %> </td>
			<td><%= cart.total_price %> </td>
			<td> <% if cart.status == false %> <%='Not yet Submitted' %> <%end %> </td>
			<td> <%= link_to "Add items", item_index_path(id:cart.id) %> | <% if cart.total_price >0 %> <%= link_to "Submit", cart_submit_cart_path(id:cart.id) %> |<%end%>  <%= link_to 'delete', cart_delete_path(id:cart.id) %> </td>
		</tr>
		<% end %>
	</tbody>
</table>
<%= link_to 'Create a new cart', cart_create_cart_path, method:'post', class:'btn btn-primary' %>

app/views/cart/new.html.erb
<table cellpadding="0" cellspacing="0" border="0" class="table table-striped table-bordered" id="data_tables">
	<thead>
		<tr>
			<th> Name </th>
			<th> Category</th>
			<th> Location</th>
			<th> Quantity</th>
			<th> Price</th>
			<th> Actions</th>
		</tr>
	</thead>

	<tbody>
		<% @products.each do |product| %>
		<tr>
			<td><%= product.name %> </td>
			<td><%= product.category_name %> </td>
			<td> <%= product.location_location_name %> </td>
			<td> <%= product.quantity%> </td>
			<td> <%= product.price%></td>
			<td> <%= cart_link(product).html_safe %> </td>
		</tr>
		<% end %>
	</tbody>
</table>

app/views/cart/product_detail.html.erb
<div class="span12 well">
	<div style="width:30%;float:left;" class="image_div">
			<%=image_tag(@product.image, size:'200x200') %>
		</div>
	<div style="width:70%;float:right;" class ="table_div">
		<table cellpadding="0" cellspacing="0" border="0" class="table table-striped table-bordered">
			<thead>
				<tr>
					<th> Field </th>
					<th> Value </th>
				</tr>
			</thead>
			<tbody>
				<tr>
					<td> Name </td>
					<td> <%= @product.name %></td>
				</tr>
				<tr>
					<td> Quantity </td>
					<td> <%= @product.quantity %></td>
				</tr>
				<tr>
					<td> Price </td>
					<td> <%= @product.price %></td>
				</tr>
				<tr>
					<td> Purchase Date </td>
					<td> <%= @product.purchase_date %></td>
				</tr>
				<tr>
					<td> Location </td>
					<td> <%= @product.location_location_name %></td>
				</tr>
				<tr>
					<td> Category </td>
					<td> <%= @product.category_name %></td>
				</tr>
			</tbody>
		</table>
	</div>
</div>
<div style="float:right;margin-right:5%;">
	<%= button_to "back", new_cart_path, method:'get', class:"btn btn-primary" %>
</div>

app/views/cart/select_quantity.html.erb
<%= form_for @product, url:{action:'create'}, method:'post' do |f| -%>
	<%= f.hidden_field :id %>
	<%= f.label :quantity, "Enter Quantity" %>
	<%= f.text_field :quantity %>
	<%= f.submit "Submit", :disable_with => 'Submiting...' %>
<% end %>