config/routes.rb
StoreManager::Application.routes.draw do
  get "unauthorized/index"
  get "unauthorized/profile"
  get "unauthorized/access_denied"
  match 'about' => 'unauthorized#about'
  devise_for :users do
    get '/'=> 'devise/sessions#new'
  end

  get 'users/edit'
  match 'users/profile' => 'user#profile'
  match 'users/edit_profile' => 'user#edit_profile'
  match 'users/update_profile' => 'user#update_profile'
  match 'unauthorized/index' => 'unauthorized#index'
  match 'users/current_request' => 'user#current_request'
  match 'users/user_cart_detail' => 'user#user_cart_detail'
  match 'users/user_cart_delete' => 'user#user_cart_delete'
  match 'users/report_list' => 'user#report_list'
  match 'users/notification' => 'user#notification'
  match 'users/notification_all' => 'user#notification_all'
  match 'users/reply_notification' => 'user#reply_notification'
  match 'users/create_reply_notification' => 'user#create_reply_notification'
  match 'users/delete_notification' => 'user#delete_notification'
  match 'users/edit_request' => 'user#edit_request'
  match 'users/update' => 'user#update'
  match 'users/destroy' => 'user#destroy'
  match 'users/compose_notification'=>'user#compose_notification'
  match 'users/create_compose_notification' => 'user#create_compose_notification'
  match 'users/change_password' => 'user#change_password'
  match 'users/update_password' => 'user#update_password'
  match 'users/send_notification_list' => 'user#send_notification_list'
  match 'users/read_notification' => 'user#read_notification'
  match 'users/notification_detail' => 'user#notification_detail'
  match 'users/move_to_trash' => 'user#move_to_trash'
  match 'users/trash_list' => 'user#trash_list'
  resources :location

  resources :category

  match 'admin/users_list' => 'admin#users_list'
  match 'admin/edit_user' => 'admin#edit_user'
  match 'admin/update_user' => 'admin#update_user'
  match 'admin/block_user' => 'admin#block_user'
  match 'admin/show_user' => 'admin#show_user'
  match 'admin/damage_list'=> 'admin#damage_list'
  match 'admin/restore_damage'=> 'admin#restore_damage'
  match 'admin/update_product' => 'admin#update_product'

  resources :product do
    collection do
      get 'move_to_damage_list'
      post 'move_to_damage'
    end
  end
  match 'product/search_result' => 'product#search_result'
  resources :cart, :except=> [:show]
  match 'cart/product_detail' => 'cart#product_detail'
  match 'cart/select_quantity' => 'cart#select_quantity'
  match 'cart/cart_detail' => 'cart#cart_detail'
  match 'cart/edit_item' => 'cart#edit_item'
  match 'cart/item_destroy' => 'cart#item_destroy'
  match 'cart/update_item' => 'cart#update_item'
  match 'cart/cart_destroy' => 'cart#cart_destroy'
  match 'cart/create_cart' => 'cart#create_cart'
  match 'cart/submit_cart' => 'cart#submit_cart'
  match 'cart/delete' => 'cart#delete'

  resources :item
  match 'item/item_detail/:id' => 'item#item_detail'
  match 'item/select_item/:id' => 'item#select_item'
  match 'item/create_item' => 'item#create_item'
  post 'item/new'
  match 'item/item_status' => 'item#item_status'

  match 'request/index' => 'request#index'
  match 'request/cart_detail' => 'request#cart_detail'
  match 'request/approve_cart' => 'request#approve_cart'
  match 'request/approve_item' => 'request#approve_item'
  match 'request/cart_delete' => 'request#cart_delete'
  match 'request/item_delete' => 'request#item_delete'
  match 'request/edit_item' => 'request#edit_item'
  match 'request/move_to_que' => 'request#move_to_que'
  match 'request/que_list' => 'request#que_list'
  match 'request/record_list' => 'request#record_list'
  match 'request/recieve_item_list' => 'request#recieve_item_list'
  match 'request/send_notification' => 'request#send_notification'
  match 'request/recieve_item' => 'request#recieve_item'
  match 'request/create_notification' => 'request#create_notification'
  match 'request/move_to_damage_list' => 'request#move_to_damage_list'
  match 'request/move_to_damage' => 'request#move_to_damage'
  post 'request/search'
  put 'request/update'

  root :to => 'devise/sessions#new'

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable,
         :lockable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me,
  								:user_role, :status
  has_one :user_detail
  has_many :carts
  has_many :notifications
end

app/controllers/user_controller.rb
class UserController < ApplicationController
before_filter :authenticate_user!

	def profile
		@user = current_user
		@user_detail = @user.user_detail
	end

	def edit_profile
		@user = current_user
		@user_detail = @user.user_detail
	end

	def update_profile
		@user = current_user
		@user_detail = @user.user_detail
		if @user_detail.update_attributes(params[:user_detail])
			flash[:notice] = "Profile Updated Succesfully"
			redirect_to users_profile_path
		else
			flash[:error] = @user_detail.errors.full_messages.to_sentence
			render 'edit_profile'
		end
	end

	def current_request
		@carts = Cart.where(:user_id=> current_user.id, :status=>true)
	end

	def user_cart_detail
		cart = Cart.find(params[:id])
		@items = cart.items
	end

	def user_cart_delete
		@cart = Cart.find(params[:id])
		if @cart.user == current_user
			if @cart.destroy
				flash[:notice] ="Cart Deleted Succesfully"
			else
				flash[:error] = @cart.errors.full_messages.to_sentence
			end
			redirect_to users_current_request_path
		else
			redirect_to unauthorized_access_denied_path
		end
	end

	def report_list
		@records = Record.of_current_user(current_user)
	end
#Notification Actions
	def notification
		@notifications = Notification.of_current_user(current_user).where(:delete_status=>false)
		@user = current_user
	end

	def trash_list
		@notifications = Notification.of_current_user(current_user).where(:delete_status=>true)
	end

	def compose_notification
		@notification = Notification.new
		@admin = User.find_by_user_role 101
	end

	def reply_notification
		@old_notification = Notification.find(params[:id])
		if current_user == @old_notification.user
			@notification = Notification.new
		else
			redirect_to unauthorized_access_denied_path
		end
	end

	def create_compose_notification
		@notification = Notification.new(params[:notification])
		@notification.from_user_id = current_user.id
		if @notification.save
			@notification.update_attributes!(:status =>true)
			flash[:notice] = "Notification Sent Succesfully"
		else
			flash[:error] = @notification.errors.full_messages.to_sentence
		end
		redirect_to users_notification_path
	end

	def send_notification_list
		user = current_user
		@notifications = Notification.where(:from_user_id=>user.id, :status=>true)
	end

	def read_notification
		@notification = Notification.find(params[:id])
		if current_user == @notification.user
			@notification.update_attributes!(:read_status=>true)
		else
			redirect_to unauthorized_access_denied_path
		end
	end

	def notification_detail
		@notification = Notification.find(params[:id])
		if current_user == @notification.sent
		else
			redirect_to unauthorized_access_denied_path
		end
	end

	def create_reply_notification
		@notification = Notification.new(params[:notification])
		@notification.from_user_id = current_user.id
		if @notification.save
			@notification.update_attributes!(:status=>true)
			flash[:notice] = "Notification Sent Succesfully"
		else
			flash[:error] = @notification.errors.full_messages.to_sentence
		end
		redirect_to users_notification_path
	end

	def move_to_trash
		@notification = Notification.find(params[:id])
		if current_user == @notification.user
			status = @notification.delete_status
			if @notification.update_attributes(:delete_status=>!status)
				flash[:notice] = "Message has been Moved Succesfully"
			else
				flash[:error] = @notification.errors.full_messages.to_sentence
			end
			redirect_to users_notification_path
		else
			redirect_to unauthorized_access_denied_path
		end
	end
# till here Notification Actions
	def edit_request
    @item = Item.find(params[:id])
  end

	def update
		@item = Item.find(params[:item][:id])
		if @item.update_attributes(params[:item])
			item_price = @item.quantity * @item.product.price
			@item.update_attributes!(:total=>item_price)
			flash[:notice] = "Successfully Updated..."
			cart = @item.cart
			@items = cart.items
			render 'user_cart_detail'
		else
			flash[:error] = @item.errors.full_messages.to_sentence
			render 'edit_request'
		end
	end

  def destroy
    @item = Item.find(params[:id])
    if @item.destroy
    	flash[:notice] = "Successfully Deleted..."
    else
    	flash[:error] = @item.errors.full_messages.to_sentence
    end
    @items = Item.of_current_cart(session[:cart_id])
    render 'index'
  end

  def change_password
  	@user = current_user
  end

  def update_password
  	@user = User.find(current_user.id)
    if @user.update_with_password(params[:user])
      sign_in @user,:bypass => true
      flash[:notice] = "Password Updated Succesfully!!!"
      redirect_to users_profile_path
    else
    	flash[:error] = @user.errors.full_messages.to_sentence
    	 redirect_to users_change_password_path
    end
  end
end

app/helpers/user_helper.rb
module UserHelper
	def current_user_request_link(cart)
		links = " "
		links += link_to 'view', action:'user_cart_detail', id:cart.id
		links += " | "
		links += link_to 'delete', action:'user_cart_delete',id:cart.id, :confirm=>'Are You Sure??', method:'delete'
		return links
	end

	def request_item_link(item)
		links = ""
		links += link_to 'Edit', action:'edit_request', id:item.id 
		return links
	end

	#def notification_link(notification)
	#	link_to 'Delete', action:'delete_notification', id:notification.id, :class=>'btn btn-primary', confirm:'Are you sure ?'
	#end
end

app/views/user/change_password.html.erb
<%= form_for @user, url:{action:'update_password'}, method:'post' do |f| -%>
  <%= f.label :current_password, "Current Password" %>
  <%= f.password_field :current_password %><br><i>(we need your current password to confirm your changes)</i><br>
  <%= f.label :password, "Password" %>
  <%= f.password_field :password %>
  <%= f.label :password_confirmation, "Confirm Password" %>
  <%= f.password_field :password_confirmation %><br>
  <%= f.submit "Change Password", :disable_with => 'processing...',class:'btn btn-primary' %>
<% end %>

app/views/user/compose_notification.html.erb
<div class="span4">
	<div class="row">
		<div style ="margin-left:50px;">
			<%= form_for @notification, url:{controller:'user', action:'create_compose_notification'},
								method:'post' do |f| -%>
				<%= f.hidden_field :user_id, value: @admin.id%>
				<%= f.hidden_field :from_user_id, value: current_user.id%>
				<%= f.label :name, "To :" %>
			  <%= text_field_tag :name,@admin.user_detail.full_name %>
			  <%= f.label :subject, "Subject :" %>
			  <%= f.text_field :subject %>
			  <%= f.label :description, "Description" %>
			  <%= f.text_area :description, size:'10x8' %>
			  <%= f.submit "Send Message", :disable_with => 'Sending...',
			  			class:"btn btn-info"%>
			<% end %>
		</div>
	</div>
</div>

app/views/user/current_request.html.erb
<table cellpadding="0" cellspacing="0" border="0" class="table table-striped table-bordered" id="data_tables">
	<thead>
		<tr>
			<th> Sl.no</th>
			<th> Cart </th>
			<th> User </th>
			<th> Position</th>
			<th> Total Price</th>
			<th> Status </th>
			<th> Actions</th>
		</tr>
	</thead>

	<tbody>
		<% @carts.each_with_index do |cart, index| %>
		<tr>
			<% cart.total_price = cart.whole_price%>
			<td><%= index+1 %> </td>
			<td> <%= cart.id%> </td>
			<td> <%= cart.user.user_detail.full_name %></td>
			<td> <%= cart.user.user_detail.position %></td>
			<td> <%= cart.total_price %></td>
			<td> <% if cart.move_to_que == false %> <%='pending'%> <%else%> <%='Moved to Que' %> <%end%> </td>
			<td><%= current_user_request_link(cart).html_safe%> </td>
		</tr>
		<% end %>
	</tbody>
</table>

app/views/user/edit_profile.html.erb
<div class="span8 well">
	<div style ="margin-left:50px;"class="row">
		<%= form_for @user_detail,url:{action:'update_profile'}, html:{multipart:true},
		 method:'post' do |f| -%>
		  <%= f.label :first_name, "First Name" %>
		  <%= f.text_field :first_name %>
		  <%= f.label :second_name, "Second Name" %>
		  <%= f.text_field :second_name %>
		  <%= f.label :contact_number, "Contact Number" %>
		  <%= f.text_field :contact_number %>
		  <%= f.label :position, "Position" %>
		  <%= f.text_field :position %>
		  <%= f.label :address, "Address" %>
		  <%= f.text_area :address, size:'5x5' %>
		  <br>
		  <%= f.file_field :image%>
		  <br>
		  <br>
		  <%= f.submit "Submit", :disable_with => 'Submiting...', class:'btn btn-primary' %>
		<% end %>
	</div>
</div>

app/views/user/edit_request.html.erb
<div class="span8 well">
	<div style="margin-left:10%;" class="row">
		<%= form_for @item, url:{:action=>'update'}, method:'put' do |f| -%>
			<%= f.hidden_field :id %>
			<%= f.label :name, "Name" %>
			<%= @item.product_name %><br>
		  <%= f.label :quantity, "Quantity" %>
		 	<%= f.select :quantity,(1..((@item.product_quantity).to_i)).to_a ,{}, :class => "span2" %>
		 	<%= f.text_field :return_date, id:'datepicker' %>
		 	<%= f.submit "update", :disable_with => 'updating...', class:'btn btn-primary' %>
		<% end %>
	</div>
</div>

app/views/user/notification.html.erb
<% if @user.user_role == 201 %>
 <%= link_to "Compose", users_compose_notification_path, class:'btn btn-primary' %>
<%else%>
<br>
<%end%>
<br>
<br>
<div class="well">
    <ul class="nav nav-tabs">
      <li class="active"><a href="/users/notification" data-toggle="tab1">Inbox</a></li>
      <li><a href="/users/send_notification_list" data-toggle="tab2">Sent Items</a></li>
      <li><a href="/users/trash_list" data-toggle="tab3">Trash</a></li>
    </ul>
  <table class="table table-condensed table-hover" id = "data_tables">
    <thead>
      <tr>
        <th class="span3">From </th>
        <th class="span6"> Subject </th>
        <th class="span2"> Message</th>
        <th class="span9"> Content</th>
        <th class="span2"> Time</th>
        <th class="span5"> Action</th>
      </tr>
    </thead>
    <tbody>
      <% @notifications.each do |notification|%>
      <tr bgcolor = <%= notification.color_display_row %> >
        <td><strong> <%= notification.sent.user_detail.full_name
         %></strong></td>
        <td><%= notification.subject %> </td>
        <td><span class="label pull-center">Notification:</span></td>
        <td><strong><%= notification.description[0,10]%>...</strong></td>
        <td><strong><%= time_ago_in_words(notification.created_at) %></strong></td>
        <td><%= link_to "Read",users_read_notification_path(id:notification.id),
         class:'btn btn-primary'%>
         <%= link_to "Delete", users_move_to_trash_path(id:notification.id),
          class:'btn btn-primary'%>
        </td>
      </tr>
      <%end%>
    </tbody>
  </table>
</div>

app/views/user/notification_detail.html.erb
<div class ="well">
	<div>
	<b>From : </b><%= @notification.sent.user_detail.full_name %>
	</div>
	<br>
	<div>
	<b>	to : </b><%= @notification.user.user_detail.full_name%>
	</div>
	<br>
	<div>
	<b>	Subject :</b><%= @notification.subject %>
	</div>
	<br>
	<b>	Message Content:</b><br>
	<div class = "message_content">
		<p>
		<%= @notification.description %></p>
	</div>
	<br>
	<b>Message sent on : </b><%= @notification.created_at.strftime("%B %d, %Y") %>
</div>
<%= link_to "Back to Sent Items", users_send_notification_list_path,
	class:'btn btn-primary' %>

app/views/user/profile.html.erb
<div class="span8 well">
	<div class="row">
		<div style="float:left;margin-left:10px;" class="span5">
			<%=image_tag(@user_detail.image) %>
		</div>
		<div style="float:right" class="span7">
			First Name :<%= @user_detail.first_name %><br>
			Second Name :<%= @user_detail.second_name %><br>
			Position : <%= @user_detail.position %><br>
			Contact number : <%= @user_detail.contact_number %><br>
			Address : <%= @user_detail.address %><br>
			<%= button_to "edit", users_edit_profile_path, class:"btn btn-primary" %>
		</div>
	</div>
</div>

app/views/user/read_notification.html.erb
<div stlye="float:left;">
 <%= link_to "Back To Inbox", users_notification_path, class:'btn btn-primary' %>
</div>
<br> <br>
<div class ="well", id ="read_notification">
	<div>
		From : <%=@notification.sent.user_detail.full_name%><br>
		<br>

		Subject : <%=@notification.subject%> <br>
		<br>
	</div>
	<div class = "message_content">
		<br>
		<strong><p><%=@notification.description%></p></strong>
	</div>
	 <%= link_to "reply", users_reply_notification_path(id:@notification.id),
	 class:'btn btn-primary' %>
 </div>

app/views/user/reply_notification.html.erb
<div class="span8 well">
	<div class="row">
		<div style ="margin-left:50px;">
			<% if @old_notification.subject%>
			<%else%>
					<%@old_notification.subject = " "%>
			<%end%>
			<%= form_for @notification, url:{controller:'user', action:'create_reply_notification'},
								method:'post' do |f| -%>
				<%= hidden_field_tag :id, @old_notification.id %>
				<%= f.hidden_field :reply_content, :value=> @old_notification.description%>
				<%= f.hidden_field :user_id, value: @old_notification.from_user_id%>
				<%= f.label :name, "To :" %>
			  <%= text_field_tag :name, @old_notification.from, readonly:true %>
			  <%= f.label :subject, "Subject :" %>
			  <%= text_field_tag :subject, @old_notification.subject, readonly:true %>
			  <br>
			  <div>
			  old Message :
			 <strong><i><%= @old_notification.description%></i></strong>
			  </div>
			  <br>
			  <br>
			  <%= f.label :subject, "Subject :" %>
			  <%= f.text_field :subject,value:"Re:"+@old_notification.subject %>
			  <%= f.label :description, "Description" %>
			  <%= f.text_area :description,id:'text', size:'10x7'%>
			  <br>
			  <%= f.submit "Send", :disable_with => 'Sending...', class:'btn btn-primary' %>
			<% end %>
		</div>
	</div>
</div>

app/views/user/report_list.html.erb
<table cellpadding="0" cellspacing="0" border="0" class="table table-striped table-bordered" id="data_tables">
	<thead>
		<tr>
			<th> Sl.no</th>
			<th> User </th>
			<th> Position</th>
			<th> Cart Id</th>
			<th> Product Name</th>
			<th> Quantity</th>
			<th> Date of purchase </th>
			<th> Date of Return </th>
			<th> Status </th>
		</tr>
	</thead>

	<tbody>
		<% @records.each_with_index do |record, index| %>
		<tr bgcolor="#A9F5F2">
			<td><%= index+1 %> </td>
			<td> <%= record.user.user_detail.full_name%> </td>
			<td> <%= record.user.user_detail.position %></td>
			<td> <%= record.cart_id %></td>
			<td> <%= record.product_name %></td>
			<td> <%= record.quantity %></td>
			<% record.status%>
			<td> <%= record.purchase_date %></td>
			<td> <%= record.return_item_date%></td>
			<td> <%= record.item_recieve_status%></td>
		</tr>
		<% end %>
	</tbody>
</table>

app/views/user/send_notification_list.html.erb
<div class = "well" >
  <ul class="nav nav-tabs">
    <li ><a href="/users/notification" data-toggle="tab1">Inbox</a></li>
    <li class="active"><a href="/users/send_notification_list" data-toggle="tab2">Sent Items</a></li>
    <li><a href="/users/trash_list" data-toggle="tab3">Trash</a></li>
  </ul>
  <table class="table table-condensed table-hover" id ="data_tables">
    <thead>
      <tr>
        <th class="span3">To </th>
        <th class="span6"> Subject </th>
        <th class="span2"> Message</th>
        <th class="span9"> Content</th>
        <th class="span2"> Time</th>
        <th class="span2"> Details </th>
      </tr>
    </thead>
    <tbody>
      <% @notifications.each do |notification|%>
        <tr bgcolor = "#E8E8E8" >
          <td><strong><%= notification.user.user_detail.full_name %> </strong></td>
          <td> <i><%= notification.subject%> </i> </td>
          <td><span class="label pull-center">content:</span></td>
          <td><strong><%= (notification.description)[0..13]%>....</strong></td>
          <td><strong><%= time_ago_in_words(notification.created_at) %></strong></td>
          <td> <%= link_to "Details", users_notification_detail_path(id:notification.id),
          class:'btn btn-primary' %> </td>
        </tr></a>
      <%end%>
    </tbody>
  </table>
</div>

app/views/user/trash_list.html.erb
<div class="well">
    <ul class="nav nav-tabs">
      <li><a href="/users/notification" data-toggle="tab1">Inbox</a></li>
      <li><a href="/users/send_notification_list" data-toggle="tab2">Sent Items</a></li>
      <li class="active"><a href="/users/trash_list" data-toggle="tab3">Trash</a></li>
    </ul>
  <table class="table table-condensed table-hover" id ="data_tables">
    <thead>
      <tr>
        <th class="span3">From </th>
        <th class="span6"> Subject </th>
        <th class="span2"> Message</th>
        <th class="span9"> Content</th>
        <th class="span2"> Time</th>
        <th class="span5"> Action</th>
      </tr>
    </thead>
    <tbody>
      <% @notifications.each do |notification|%>
      <tr bgcolor = <%= notification.color_display_row %> >
        <td><strong> <%= notification.sent.user_detail.full_name
         %></strong></td>
        <td><%= notification.subject %> </td>
        <td><span class="label pull-center">Notification:</span></td>
        <td><strong><%= notification.description[0,10]%>...</strong></td>
        <td><strong><%= time_ago_in_words(notification.created_at) %></strong></td>
        <td><%= link_to "Read",users_read_notification_path(id:notification.id),
         class:'btn btn-primary'%> <%= link_to "Undelete",
          users_move_to_trash_path(id:notification.id),class:'btn btn-primary' %> </td>
      </tr>
      <%end%>
    </tbody>
  </table>
</div>

app/views/user/user_cart_detail.html.erb
<table cellpadding="0" cellspacing="0" border="0" class="table table-striped table-bordered" id="data_tables">
	<thead>
		<tr>
			<th> Product </th>
			<th> Price/Unit</th>
			<th> Quantity</th>
			<th> Total </th>
			<th> Return Date</th>
			<th> Actions</th>
		</tr>
	</thead>

	<tbody>
		<% @items.each do |item| %>
		<tr>
			<td><%= item.product_name %> </td>
			<td> <%= item.product.price%></td>
			<td> <%= item.quantity %></td>
			<td> <%= item.total %></td>
			<td> <%= item.return_date %></td>
			<td> <%=request_item_link(item).html_safe%></td>
		</tr>
		<% end %>
	</tbody>
</table>
<%= link_to "Back", users_current_request_path, class:'btn btn-primary' %>