config/routes.rb
StoreManager::Application.routes.draw do
  get "unauthorized/index"
  get "unauthorized/profile"
  get "unauthorized/access_denied"
  match 'about' => 'unauthorized#about'
  devise_for :users do
    get '/'=> 'devise/sessions#new'
  end

  get 'users/edit'
  match 'users/profile' => 'user#profile'
  match 'users/edit_profile' => 'user#edit_profile'
  match 'users/update_profile' => 'user#update_profile'
  match 'unauthorized/index' => 'unauthorized#index'
  match 'users/current_request' => 'user#current_request'
  match 'users/user_cart_detail' => 'user#user_cart_detail'
  match 'users/user_cart_delete' => 'user#user_cart_delete'
  match 'users/report_list' => 'user#report_list'
  match 'users/notification' => 'user#notification'
  match 'users/notification_all' => 'user#notification_all'
  match 'users/reply_notification' => 'user#reply_notification'
  match 'users/create_reply_notification' => 'user#create_reply_notification'
  match 'users/delete_notification' => 'user#delete_notification'
  match 'users/edit_request' => 'user#edit_request'
  match 'users/update' => 'user#update'
  match 'users/destroy' => 'user#destroy'
  match 'users/compose_notification'=>'user#compose_notification'
  match 'users/create_compose_notification' => 'user#create_compose_notification'
  match 'users/change_password' => 'user#change_password'
  match 'users/update_password' => 'user#update_password'
  match 'users/send_notification_list' => 'user#send_notification_list'
  match 'users/read_notification' => 'user#read_notification'
  match 'users/notification_detail' => 'user#notification_detail'
  match 'users/move_to_trash' => 'user#move_to_trash'
  match 'users/trash_list' => 'user#trash_list'
  resources :location

  resources :category

  match 'admin/users_list' => 'admin#users_list'
  match 'admin/edit_user' => 'admin#edit_user'
  match 'admin/update_user' => 'admin#update_user'
  match 'admin/block_user' => 'admin#block_user'
  match 'admin/show_user' => 'admin#show_user'
  match 'admin/damage_list'=> 'admin#damage_list'
  match 'admin/restore_damage'=> 'admin#restore_damage'
  match 'admin/update_product' => 'admin#update_product'

  resources :product do
    collection do
      get 'move_to_damage_list'
      post 'move_to_damage'
    end
  end
  match 'product/search_result' => 'product#search_result'
  resources :cart, :except=> [:show]
  match 'cart/product_detail' => 'cart#product_detail'
  match 'cart/select_quantity' => 'cart#select_quantity'
  match 'cart/cart_detail' => 'cart#cart_detail'
  match 'cart/edit_item' => 'cart#edit_item'
  match 'cart/item_destroy' => 'cart#item_destroy'
  match 'cart/update_item' => 'cart#update_item'
  match 'cart/cart_destroy' => 'cart#cart_destroy'
  match 'cart/create_cart' => 'cart#create_cart'
  match 'cart/submit_cart' => 'cart#submit_cart'
  match 'cart/delete' => 'cart#delete'

  resources :item
  match 'item/item_detail/:id' => 'item#item_detail'
  match 'item/select_item/:id' => 'item#select_item'
  match 'item/create_item' => 'item#create_item'
  post 'item/new'
  match 'item/item_status' => 'item#item_status'

  match 'request/index' => 'request#index'
  match 'request/cart_detail' => 'request#cart_detail'
  match 'request/approve_cart' => 'request#approve_cart'
  match 'request/approve_item' => 'request#approve_item'
  match 'request/cart_delete' => 'request#cart_delete'
  match 'request/item_delete' => 'request#item_delete'
  match 'request/edit_item' => 'request#edit_item'
  match 'request/move_to_que' => 'request#move_to_que'
  match 'request/que_list' => 'request#que_list'
  match 'request/record_list' => 'request#record_list'
  match 'request/recieve_item_list' => 'request#recieve_item_list'
  match 'request/send_notification' => 'request#send_notification'
  match 'request/recieve_item' => 'request#recieve_item'
  match 'request/create_notification' => 'request#create_notification'
  match 'request/move_to_damage_list' => 'request#move_to_damage_list'
  match 'request/move_to_damage' => 'request#move_to_damage'
  post 'request/search'
  put 'request/update'

  root :to => 'devise/sessions#new'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "StoreManager" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'images/favicon.ico', :rel => 'shortcut icon' %>
  </head>
  <body>

    <div class="navbar navbar-fluid-top">
      <div class="navbar-inner">
        <div class="container-fluid">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="#">StoreManager</a>
          <div class="container-fluid nav-collapse">
            <ul class="nav">
              <% if user_signed_in?%>
                <li><%= link_to "Home", users_profile_path%></li>
                <%else%>
                <li><%= link_to "Home", "/"%></li>
              <%end%>
              <li><%= link_to "About", "/about"  %></li>
            </ul>
            <ul class="nav pull-right">
              <% if user_signed_in? %>
                <li><%= link_to "Sign Out", destroy_user_session_path, method:'delete'%></li>
              <% else %>
                <li><%= link_to "Sign In", new_user_session_path %></li>
              <% end %>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container-fluid">
      <div class="row-fluid">
        <div class="span3">
        <% if user_signed_in? %>
          <div class="well sidebar-nav">
            <ul class="nav nav-list">
              <li class="nav-header">Sidebar</li>
                <li class="<%= 'active' if current_page?(users_profile_path) %>">
                  <%= link_to "Profile", users_profile_path  %></li>
                <% if is_admin %>
                  <li class="<%= 'active' if current_page?(location_index_path) %>">
                    <%= link_to 'Location', location_index_path %></li>
                  <li class="<%= 'active' if current_page?(category_index_path) %>">
                    <%= link_to 'Category', category_index_path %></li>
                  <li class="<%= 'active' if current_page?(product_index_path) %>">
                    <%= link_to 'Product', product_index_path %></li>
                  <li class="<%= 'active' if current_page?(admin_users_list_path) %>">
                    <%= link_to 'Users', admin_users_list_path %></li>
                  <li class="<%= 'active' if current_page?(request_que_list_path) %>">
                    <%= link_to 'Que List', request_que_list_path %></li>
                  <li class="<%= 'active' if current_page?(request_index_path) %>">
                    <%= link_to 'Requests', request_index_path %></li>
                  <li class="<%= 'active' if current_page?(request_record_list_path) %>">
                    <%= link_to 'Records', request_record_list_path %></li>
                  <li class="<%= 'active' if current_page?(request_recieve_item_list_path) %>">
                     <%= link_to 'Recieve Items', request_recieve_item_list_path %>
                  </li>
                  <li class="<%= 'active' if current_page?(users_notification_path) %>">
                    <%= link_to 'Notification', users_notification_path %></li>
                  <li class="<%= 'active' if current_page?(admin_damage_list_path) %>"> <%= link_to 'Damage List', admin_damage_list_path %></li>
                  <li class="<%= 'active' if current_page?(users_change_password_path) %>" > <%= link_to 'Change password', users_change_password_path %> </li>
                <%elsif current_user.status == true%>
                  <li class="<%= 'active' if current_page?(cart_index_path) %>">
                    <%= link_to 'Request item',cart_index_path%></li>
                  <li class="<%= 'active' if current_page?(users_current_request_path) %>">
                    <%= link_to 'Requests', users_current_request_path %></li>
                  <li class="<%= 'active' if current_page?(users_report_list_path) %>">
                    <%= link_to 'Reports', users_report_list_path %></li>
                  <li class="<%= 'active' if current_page?(users_notification_path) %>">
                    <%= link_to 'Notification', users_notification_path %></li>
                  <li class="<%= 'active' if current_page?(users_change_password_path) %>" > <%= link_to 'Change password', users_change_password_path %> </li>
                <%else%>
                <li> <%= link_to 'Status', unauthorized_profile_path %> </li>
                <%end%>
            </ul>
          </div><!--/.well -->
        <%end%>
        </div><!--/span-->

        <div class="span9">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
      </div><!--/row-->
      <footer>

        <p>&copy; Developed by <a href="https://bitbucket.org/ashikajith" title="Ashik Ajith">Ashik Ajith</a> for <a href="http://rubykitchen.in" title="RubyKitchen">Ruby Kitchen</a></p>
      </footer>

    </div> <!-- /container -->

    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>

  </body>
</html>